sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tQhVfuuJoMJg47eicRM
    access-key-secret: 7BAmXvTlGQKvTqJnXyydmvZ0RrVFxp
    bucket-name: appointment-register-cpg
